trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python37Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
      Python37Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-latest'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Python38Windows:
        imageName: 'windows-latest'
        python.version: '3.8'
      Python38Mac:
        imageName: 'macos-latest'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      Python39Windows:
        imageName: 'windows-latest'
        python.version: '3.9'
      Python39Mac:
        imageName: 'macos-latest'
        python.version: '3.9'
      Python310Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.10'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
      Python310Mac:
        imageName: 'macos-latest'
        python.version: '3.10'
      Python311Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.11'
      Python311Windows:
        imageName: 'windows-latest'
        python.version: '3.11'
      Python311Mac:
        imageName: 'macos-latest'
        python.version: '3.11'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      allowUnstable: true

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python setup.py build_ext --inplace
      python setup.py sdist
    displayName: 'Build sdist'

  - script: |
      pip freeze > installed.txt
      pip uninstall -y -r installed.txt
    displayName: 'Uninstall all packages'

  - script: pip install dist/*.tar.gz
    condition: in( variables['Agent.OS'], 'Linux', 'Darwin')
    displayName: 'Install from sdist (Linux, Mac)'

  - script: pip install -e .
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install with pip (Windows)'

  - script: |
      pip install -r requirements.txt
      python -X dev -m pytest preshed
    displayName: 'Run tests'
